version: '3.8'

services:
  web:
    build: .
    ports:
      - 8091:8091
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5433:5433
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
